### ISSUE TITLE
totp_compares reads garbage from memory

### ISSUE THREAD

**Issue by feliwir** [tilkinsc/COTP#11]
Hey,

an issue related to string / keylength:
`totp_compares` reads beyond the end of the passed key. See https://github.com/tilkinsc/COTP/blob/master/cotp.c#L161
A fixed length of 8 is used - meaning when we have a DIGITCOUNT of 6 this will read 2 more characters with undefined content, resulting in a possible failure. This should check for the digitcount specified in `otp_new`

**Comment by tilkinsc** [comment]
calloc returns 0'd memory. This 0'd memory is in the same bounds as a opt_generation call. There is no problem. Digit count has nothing to do with this.

**Comment by tilkinsc** [comment]
I will be removing totp_compares and totp_verifys and the i equiv in a little bit. They are being forced down to requiring a string. It is invalid to have a code who is of a length that doesn't have '0' character where null.

Key length can't be dynamic not due to the digit count, but I incorrectly wrote the handler for `int otp_int_to_bytestring(long integer, char* out_str)` in which it doesn't cover the full range of 8 bytes. This causes errors in some codes and codes bigger than 6, interestingly up to 8.

The undefined content being read is actually preplanned, but incorrectly implemented. I was using ints and failed to correctly account for data types. I am also using non-standard datatypes which is unacceptable.

**Comment by tilkinsc** [comment]
8036cd8 fixes this
